CREATE TABLE t_order (
    id              BIGSERIAL PRIMARY KEY,
    tenant_id       BIGINT NOT NULL,
    order_no        VARCHAR(32) NOT NULL,
    user_id         BIGINT NOT NULL,
    merchant_id     BIGINT,
    order_type      SMALLINT NOT NULL,
    status          SMALLINT NOT NULL DEFAULT 0,
    total_amount    DECIMAL(10,2) NOT NULL,
    discount_amount DECIMAL(10,2) DEFAULT 0,
    pay_amount      DECIMAL(10,2) NOT NULL,
    pay_type        SMALLINT,
    pay_time        BIGINT,
    pay_no          VARCHAR(64),
    receiver_name   VARCHAR(50),
    receiver_phone  VARCHAR(20),
    receiver_address VARCHAR(300),
    dining_type     SMALLINT,
    table_no        VARCHAR(20),
    remark          VARCHAR(500),
    campaign_id     BIGINT,
    distributor_id  BIGINT,
    extra           JSONB DEFAULT '{}',
    created_at      BIGINT NOT NULL,
    created_by      BIGINT,
    updated_at      BIGINT NOT NULL,
    updated_by      BIGINT,
    idempotent_key  VARCHAR(64),
    UNIQUE(tenant_id, order_no)
);

CREATE TABLE t_order_item (
    id              BIGSERIAL PRIMARY KEY,
    tenant_id       BIGINT NOT NULL,
    order_id        BIGINT NOT NULL,
    spu_id          BIGINT NOT NULL,
    sku_id          BIGINT NOT NULL,
    sku_name        VARCHAR(200),
    sku_image       VARCHAR(500),
    spec_values     JSONB,
    price           DECIMAL(10,2) NOT NULL,
    quantity        INT NOT NULL,
    subtotal        DECIMAL(10,2) NOT NULL,
    created_at      BIGINT NOT NULL,
    created_by      BIGINT,
    updated_at      BIGINT NOT NULL,
    updated_by      BIGINT,
    idempotent_key  VARCHAR(64)
);
